### PR TITLE
[semver:minor] Remove overwrite parameter

### LINKED ISSUE #7: Unclear that overwrite means --delete for sync command
**Orb Version**
All versions

**Describe the bug**
This is more a question/discussion about the `overwrite` parameter of the `sync` command. It is not obvious what this parameter actually does.

`aws s3 sync` will _aways_ overwrite files that already exist in the bucket if the files being sync'd are newer.

What the `overwrite` parameter is actually doing is adding the `--delete` flag to the s3 command. This has a _very_ different meaning to what you would expect from overwrite. `--delete` will remove any files that already existed on the bucket but are not in the directory being sync'd. In other words, existing files will be overwritten _regardless_ of the overwrite parameter, but this parameter causes files that may already exist in the bucket to be removed if they are not found in the source directory for the sync command.

Ideally, the `overwrite` parameter would be renamed to `delete` to match what it is actually doing to the `s3 sync command`. 

This unexpected behaviour caused our web app to break due to files being deleted from the bucket when running the sync command with `overwrite: true`.

**Expected behavior**

Either the documentation for this orb makes it clear that `overwrite: true` means `--delete`, or the parameter be renamed to `delete`.

### PR DESCRIPTION
**Pull request by gmemstr**
See #7

### CODE REVIEW

**Review by lokst — APPROVED** [review]

**Comment by tobypinder** [comment]
Semver - minor for an API incompatible change?

**Comment by masone** [comment]
For reference, here's the error one gets who still passes the argument

```
#!/bin/sh -eo pipefail
# Error calling workflow: 'ads_prod'
# Error calling job: 'store_homepage_ads_prod'
# Error calling command: 'aws-s3/sync'
# Unexpected argument(s): overwrite
```

It might be worth pointing out the upgrade path in the changelog. something along:
- if you intend to overwrite files, remove the argument `overwrite`. newer files will always be overwritten on the target by default
- if you intend to delete existing files from the target when they're not present in the source, pass `arguments.delete` to maintain the behavior from the previous version

**Comment by gmemstr** [comment]
@tobypinder Generally speaking, we change major semver when something is a major breakage or behaviour change. This is a relatively small change, so we opted for a minor - this allows users using `1.0.x` versions to ignore the change. We typically recommend versioning orbs in configurations to the nearest patch version, or minor if patch is determined to be too granular.

**Comment by masone** [comment]
Thanks for your comment @gmemstr - this _was_ a breaking change for anyone using this option. circle fails validating the configuration of the orb before even running the task

**Comment by gmemstr** [comment]
@masone Yup, understood - that's on me, and I apologize for the oversight. There are two options here - either we keep it the same, with no remediation, or we roll a new minor or patch version to revert this change, and push the change out again as a major change. If we opt for the second option, there may be some additional changes for the major version.

**Pull request merged**
